version: "3.8"

services:
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=adminpass
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgresdb
      - redis
    ports:
      - "8000:8000"

#  celery:
#    build: .
#    command: celery -A Test_Rocket worker -l info
#    volumes:
#      - .:/usr/src/app
#    depends_on:
#      - redis

  redis:
    image: redis:latest


