version: "3.8"

services:
  db:
    image: "postgres:12"
    ports:
      - "5432:5432"

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django
    command: bash -c "python manage.py create_superuser
              && python /usr/src/app/manage.py makemigrations --no-input
              && python /usr/src/app/manage.py migrate --no-input
              && python /usr/src/app/manage.py fake
              && python /usr/src/app/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db
    ports:
      - "8000:8000"

  celery:
    restart: always
    build: .
    container_name: celery
    command: celery -A Test_Rocket worker -E -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - django
      - redis

  celery-beat:
    restart: always
    build: .
    container_name: celery-beat
    command: celery -A Test_Rocket beat -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - django
      - redis

  redis:
    image: redis:latest
    container_name: radis
