# Generated by Django 3.2 on 2021-06-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Должность')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('second_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='Отчество')),
                ('date_of_employment', models.DateField(verbose_name='Дата приёма на работу')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Заработная плата')),
                ('total_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Всего заплатили')),
                ('level', models.CharField(choices=[('Level_1', 'Первый уровень'), ('Level_2', 'Второй уровень'), ('Level_3', 'Третий уровень'), ('Level_4', 'Четвёртый уровень'), ('Level_5', 'Пятый уровень')], max_length=20, null=True, verbose_name='Уровень')),
                ('chief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Начальник')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employee.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
